package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"

	"github.com/Matthew11K/Comments-Service/internal/adapters/graphql/generated"
	"github.com/Matthew11K/Comments-Service/internal/adapters/graphql/graph/model"
	"github.com/Matthew11K/Comments-Service/internal/application"
	"github.com/Matthew11K/Comments-Service/internal/domain"
	"github.com/google/uuid"
)

// Replies is the resolver for the replies field.
func (r *commentResolver) Replies(ctx context.Context, obj *model.Comment, first int, after *string) (*model.CommentConnection, error) {
	state, err := requestStateFromContext(ctx)
	if err != nil {
		return nil, err
	}

	loaderThunk := state.loaders.commentConnections.Load(ctx, commentConnectionKey{
		Scope: scopeComment,
		ID:    obj.ID,
		First: first,
		After: stringValue(after),
	})
	connection, err := loaderThunk()
	if err != nil {
		return nil, err
	}

	if err := registerCommentConnectionResolver(ctx, connection, func(ctx context.Context) (int, error) {
		countThunk := state.loaders.replyCounts.Load(ctx, obj.ID)
		return countThunk()
	}); err != nil {
		return nil, err
	}

	return connection, nil
}

// TotalCount is the resolver for the totalCount field.
func (r *commentConnectionResolver) TotalCount(ctx context.Context, obj *model.CommentConnection) (int, error) {
	return resolveCommentConnectionCount(ctx, obj)
}

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.CreatePostInput) (*model.Post, error) {
	post, err := r.posts.CreatePost(ctx, application.CreatePostInput{
		AuthorID: domain.NewUserID(input.AuthorID),
		Title:    input.Title,
		Content:  input.Content,
	})
	if err != nil {
		return nil, err
	}

	return newPostModel(post), nil
}

// SetCommentsEnabled is the resolver for the setCommentsEnabled field.
func (r *mutationResolver) SetCommentsEnabled(ctx context.Context, postID uuid.UUID, enabled bool) (*model.Post, error) {
	actorID, err := actorFromContext(ctx)
	if err != nil {
		return nil, err
	}

	post, err := r.posts.SetCommentsEnabled(ctx, application.SetCommentsEnabledInput{
		PostID:  domain.NewPostID(postID),
		ActorID: actorID,
		Enabled: enabled,
	})
	if err != nil {
		return nil, err
	}

	return newPostModel(post), nil
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, input model.CreateCommentInput) (*model.Comment, error) {
	var parentID *domain.CommentID
	if input.ParentID != nil {
		value := domain.NewCommentID(*input.ParentID)
		parentID = &value
	}

	comment, err := r.comments.CreateComment(ctx, application.CreateCommentInput{
		PostID:   domain.NewPostID(input.PostID),
		ParentID: parentID,
		AuthorID: domain.NewUserID(input.AuthorID),
		Body:     input.Body,
	})
	if err != nil {
		return nil, err
	}

	return newCommentModel(comment), nil
}

// Comments is the resolver for the comments field.
func (r *postResolver) Comments(ctx context.Context, obj *model.Post, first int, after *string) (*model.CommentConnection, error) {
	state, err := requestStateFromContext(ctx)
	if err != nil {
		return nil, err
	}

	loaderThunk := state.loaders.commentConnections.Load(ctx, commentConnectionKey{
		Scope: scopePost,
		ID:    obj.ID,
		First: first,
		After: stringValue(after),
	})
	connection, err := loaderThunk()
	if err != nil {
		return nil, err
	}

	if err := registerCommentConnectionResolver(ctx, connection, func(ctx context.Context) (int, error) {
		countThunk := state.loaders.topLevelCounts.Load(ctx, obj.ID)
		return countThunk()
	}); err != nil {
		return nil, err
	}

	return connection, nil
}

// TotalCount is the resolver for the totalCount field.
func (r *postConnectionResolver) TotalCount(ctx context.Context, obj *model.PostConnection) (int, error) {
	return resolvePostConnectionCount(ctx, obj)
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, first int, after *string) (*model.PostConnection, error) {
	page, err := domain.NewPageInput(first, after)
	if err != nil {
		return nil, err
	}

	posts, err := r.posts.ListPosts(ctx, page)
	if err != nil {
		return nil, err
	}

	connection, err := newPostConnection(posts)
	if err != nil {
		return nil, err
	}

	if err := registerPostConnectionResolver(ctx, connection, r.posts.CountPosts); err != nil {
		return nil, err
	}

	return connection, nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id uuid.UUID) (*model.Post, error) {
	post, err := r.posts.GetPost(ctx, domain.NewPostID(id))
	if err != nil {
		return nil, err
	}

	return newPostModel(post), nil
}

// CommentAdded is the resolver for the commentAdded field.
func (r *subscriptionResolver) CommentAdded(ctx context.Context, postID uuid.UUID) (<-chan *model.Comment, error) {
	events, unsubscribe, err := r.events.Subscribe(ctx, domain.NewPostID(postID))
	if err != nil {
		return nil, err
	}

	result := make(chan *model.Comment)
	go func() {
		defer unsubscribe()
		defer close(result)

		for {
			select {
			case <-ctx.Done():
				return
			case event, ok := <-events:
				if !ok {
					return
				}

				comment, err := r.comments.GetComment(ctx, event.CommentID)
				if err != nil {
					r.logger.ErrorContext(ctx, "load comment for subscription", "error", err, "comment_id", event.CommentID.String())
					continue
				}

				select {
				case result <- newCommentModel(comment):
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return result, nil
}

// Comment returns generated.CommentResolver implementation.
func (r *Resolver) Comment() generated.CommentResolver { return &commentResolver{r} }

// CommentConnection returns generated.CommentConnectionResolver implementation.
func (r *Resolver) CommentConnection() generated.CommentConnectionResolver {
	return &commentConnectionResolver{r}
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Post returns generated.PostResolver implementation.
func (r *Resolver) Post() generated.PostResolver { return &postResolver{r} }

// PostConnection returns generated.PostConnectionResolver implementation.
func (r *Resolver) PostConnection() generated.PostConnectionResolver {
	return &postConnectionResolver{r}
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type commentResolver struct{ *Resolver }
type commentConnectionResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type postResolver struct{ *Resolver }
type postConnectionResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
