// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/google/uuid"
)

type Comment struct {
	ID        uuid.UUID          `json:"id"`
	PostID    uuid.UUID          `json:"postId"`
	ParentID  *uuid.UUID         `json:"parentId,omitempty"`
	AuthorID  uuid.UUID          `json:"authorId"`
	Body      string             `json:"body"`
	CreatedAt time.Time          `json:"createdAt"`
	Replies   *CommentConnection `json:"replies"`
}

type CommentConnection struct {
	TotalCount int            `json:"totalCount"`
	Edges      []*CommentEdge `json:"edges"`
	PageInfo   *PageInfo      `json:"pageInfo"`
}

type CommentEdge struct {
	Cursor string   `json:"cursor"`
	Node   *Comment `json:"node"`
}

type CreateCommentInput struct {
	PostID   uuid.UUID  `json:"postId"`
	ParentID *uuid.UUID `json:"parentId,omitempty"`
	AuthorID uuid.UUID  `json:"authorId"`
	Body     string     `json:"body"`
}

type CreatePostInput struct {
	AuthorID uuid.UUID `json:"authorId"`
	Title    string    `json:"title"`
	Content  string    `json:"content"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage bool    `json:"hasNextPage"`
	EndCursor   *string `json:"endCursor,omitempty"`
}

type Post struct {
	ID              uuid.UUID          `json:"id"`
	AuthorID        uuid.UUID          `json:"authorId"`
	Title           string             `json:"title"`
	Content         string             `json:"content"`
	CommentsEnabled bool               `json:"commentsEnabled"`
	CreatedAt       time.Time          `json:"createdAt"`
	Comments        *CommentConnection `json:"comments"`
}

type PostConnection struct {
	TotalCount int         `json:"totalCount"`
	Edges      []*PostEdge `json:"edges"`
	PageInfo   *PageInfo   `json:"pageInfo"`
}

type PostEdge struct {
	Cursor string `json:"cursor"`
	Node   *Post  `json:"node"`
}

type Query struct {
}

type Subscription struct {
}
