// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package applicationmocks

import (
	"context"

	"github.com/Matthew11K/Comments-Service/internal/application"
	"github.com/Matthew11K/Comments-Service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewCommentEventSubscriber creates a new instance of CommentEventSubscriber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommentEventSubscriber(t interface {
	mock.TestingT
	Cleanup(func())
}) *CommentEventSubscriber {
	mock := &CommentEventSubscriber{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CommentEventSubscriber is an autogenerated mock type for the CommentEventSubscriber type
type CommentEventSubscriber struct {
	mock.Mock
}

type CommentEventSubscriber_Expecter struct {
	mock *mock.Mock
}

func (_m *CommentEventSubscriber) EXPECT() *CommentEventSubscriber_Expecter {
	return &CommentEventSubscriber_Expecter{mock: &_m.Mock}
}

// Subscribe provides a mock function for the type CommentEventSubscriber
func (_mock *CommentEventSubscriber) Subscribe(ctx context.Context, postID domain.PostID) (<-chan application.CommentAddedEvent, func(), error) {
	ret := _mock.Called(ctx, postID)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 <-chan application.CommentAddedEvent
	var r1 func()
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PostID) (<-chan application.CommentAddedEvent, func(), error)); ok {
		return returnFunc(ctx, postID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PostID) <-chan application.CommentAddedEvent); ok {
		r0 = returnFunc(ctx, postID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan application.CommentAddedEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.PostID) func()); ok {
		r1 = returnFunc(ctx, postID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(func())
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, domain.PostID) error); ok {
		r2 = returnFunc(ctx, postID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// CommentEventSubscriber_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type CommentEventSubscriber_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - ctx context.Context
//   - postID domain.PostID
func (_e *CommentEventSubscriber_Expecter) Subscribe(ctx interface{}, postID interface{}) *CommentEventSubscriber_Subscribe_Call {
	return &CommentEventSubscriber_Subscribe_Call{Call: _e.mock.On("Subscribe", ctx, postID)}
}

func (_c *CommentEventSubscriber_Subscribe_Call) Run(run func(ctx context.Context, postID domain.PostID)) *CommentEventSubscriber_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PostID
		if args[1] != nil {
			arg1 = args[1].(domain.PostID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CommentEventSubscriber_Subscribe_Call) Return(commentAddedEventCh <-chan application.CommentAddedEvent, fn func(), err error) *CommentEventSubscriber_Subscribe_Call {
	_c.Call.Return(commentAddedEventCh, fn, err)
	return _c
}

func (_c *CommentEventSubscriber_Subscribe_Call) RunAndReturn(run func(ctx context.Context, postID domain.PostID) (<-chan application.CommentAddedEvent, func(), error)) *CommentEventSubscriber_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}
