// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package applicationmocks

import (
	"context"

	"github.com/Matthew11K/Comments-Service/internal/application"
	"github.com/Matthew11K/Comments-Service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewCommentEvents creates a new instance of CommentEvents. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommentEvents(t interface {
	mock.TestingT
	Cleanup(func())
}) *CommentEvents {
	mock := &CommentEvents{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CommentEvents is an autogenerated mock type for the CommentEvents type
type CommentEvents struct {
	mock.Mock
}

type CommentEvents_Expecter struct {
	mock *mock.Mock
}

func (_m *CommentEvents) EXPECT() *CommentEvents_Expecter {
	return &CommentEvents_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type CommentEvents
func (_mock *CommentEvents) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CommentEvents_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type CommentEvents_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *CommentEvents_Expecter) Close() *CommentEvents_Close_Call {
	return &CommentEvents_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *CommentEvents_Close_Call) Run(run func()) *CommentEvents_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CommentEvents_Close_Call) Return(err error) *CommentEvents_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CommentEvents_Close_Call) RunAndReturn(run func() error) *CommentEvents_Close_Call {
	_c.Call.Return(run)
	return _c
}

// PublishCommentAdded provides a mock function for the type CommentEvents
func (_mock *CommentEvents) PublishCommentAdded(ctx context.Context, event application.CommentAddedEvent) {
	_mock.Called(ctx, event)
	return
}

// CommentEvents_PublishCommentAdded_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishCommentAdded'
type CommentEvents_PublishCommentAdded_Call struct {
	*mock.Call
}

// PublishCommentAdded is a helper method to define mock.On call
//   - ctx context.Context
//   - event application.CommentAddedEvent
func (_e *CommentEvents_Expecter) PublishCommentAdded(ctx interface{}, event interface{}) *CommentEvents_PublishCommentAdded_Call {
	return &CommentEvents_PublishCommentAdded_Call{Call: _e.mock.On("PublishCommentAdded", ctx, event)}
}

func (_c *CommentEvents_PublishCommentAdded_Call) Run(run func(ctx context.Context, event application.CommentAddedEvent)) *CommentEvents_PublishCommentAdded_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 application.CommentAddedEvent
		if args[1] != nil {
			arg1 = args[1].(application.CommentAddedEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CommentEvents_PublishCommentAdded_Call) Return() *CommentEvents_PublishCommentAdded_Call {
	_c.Call.Return()
	return _c
}

func (_c *CommentEvents_PublishCommentAdded_Call) RunAndReturn(run func(ctx context.Context, event application.CommentAddedEvent)) *CommentEvents_PublishCommentAdded_Call {
	_c.Run(run)
	return _c
}

// Subscribe provides a mock function for the type CommentEvents
func (_mock *CommentEvents) Subscribe(ctx context.Context, postID domain.PostID) (<-chan application.CommentAddedEvent, func(), error) {
	ret := _mock.Called(ctx, postID)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 <-chan application.CommentAddedEvent
	var r1 func()
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PostID) (<-chan application.CommentAddedEvent, func(), error)); ok {
		return returnFunc(ctx, postID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PostID) <-chan application.CommentAddedEvent); ok {
		r0 = returnFunc(ctx, postID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan application.CommentAddedEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.PostID) func()); ok {
		r1 = returnFunc(ctx, postID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(func())
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, domain.PostID) error); ok {
		r2 = returnFunc(ctx, postID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// CommentEvents_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type CommentEvents_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - ctx context.Context
//   - postID domain.PostID
func (_e *CommentEvents_Expecter) Subscribe(ctx interface{}, postID interface{}) *CommentEvents_Subscribe_Call {
	return &CommentEvents_Subscribe_Call{Call: _e.mock.On("Subscribe", ctx, postID)}
}

func (_c *CommentEvents_Subscribe_Call) Run(run func(ctx context.Context, postID domain.PostID)) *CommentEvents_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PostID
		if args[1] != nil {
			arg1 = args[1].(domain.PostID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CommentEvents_Subscribe_Call) Return(commentAddedEventCh <-chan application.CommentAddedEvent, fn func(), err error) *CommentEvents_Subscribe_Call {
	_c.Call.Return(commentAddedEventCh, fn, err)
	return _c
}

func (_c *CommentEvents_Subscribe_Call) RunAndReturn(run func(ctx context.Context, postID domain.PostID) (<-chan application.CommentAddedEvent, func(), error)) *CommentEvents_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}
