// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package applicationmocks

import (
	"context"

	"github.com/Matthew11K/Comments-Service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewCommentRepository creates a new instance of CommentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CommentRepository {
	mock := &CommentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CommentRepository is an autogenerated mock type for the CommentRepository type
type CommentRepository struct {
	mock.Mock
}

type CommentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CommentRepository) EXPECT() *CommentRepository_Expecter {
	return &CommentRepository_Expecter{mock: &_m.Mock}
}

// BatchCountReplies provides a mock function for the type CommentRepository
func (_mock *CommentRepository) BatchCountReplies(ctx context.Context, parentIDs []domain.CommentID) (map[domain.CommentID]int, error) {
	ret := _mock.Called(ctx, parentIDs)

	if len(ret) == 0 {
		panic("no return value specified for BatchCountReplies")
	}

	var r0 map[domain.CommentID]int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.CommentID) (map[domain.CommentID]int, error)); ok {
		return returnFunc(ctx, parentIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.CommentID) map[domain.CommentID]int); ok {
		r0 = returnFunc(ctx, parentIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[domain.CommentID]int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []domain.CommentID) error); ok {
		r1 = returnFunc(ctx, parentIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CommentRepository_BatchCountReplies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchCountReplies'
type CommentRepository_BatchCountReplies_Call struct {
	*mock.Call
}

// BatchCountReplies is a helper method to define mock.On call
//   - ctx context.Context
//   - parentIDs []domain.CommentID
func (_e *CommentRepository_Expecter) BatchCountReplies(ctx interface{}, parentIDs interface{}) *CommentRepository_BatchCountReplies_Call {
	return &CommentRepository_BatchCountReplies_Call{Call: _e.mock.On("BatchCountReplies", ctx, parentIDs)}
}

func (_c *CommentRepository_BatchCountReplies_Call) Run(run func(ctx context.Context, parentIDs []domain.CommentID)) *CommentRepository_BatchCountReplies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []domain.CommentID
		if args[1] != nil {
			arg1 = args[1].([]domain.CommentID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CommentRepository_BatchCountReplies_Call) Return(commentIDToInt map[domain.CommentID]int, err error) *CommentRepository_BatchCountReplies_Call {
	_c.Call.Return(commentIDToInt, err)
	return _c
}

func (_c *CommentRepository_BatchCountReplies_Call) RunAndReturn(run func(ctx context.Context, parentIDs []domain.CommentID) (map[domain.CommentID]int, error)) *CommentRepository_BatchCountReplies_Call {
	_c.Call.Return(run)
	return _c
}

// BatchCountTopLevel provides a mock function for the type CommentRepository
func (_mock *CommentRepository) BatchCountTopLevel(ctx context.Context, postIDs []domain.PostID) (map[domain.PostID]int, error) {
	ret := _mock.Called(ctx, postIDs)

	if len(ret) == 0 {
		panic("no return value specified for BatchCountTopLevel")
	}

	var r0 map[domain.PostID]int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.PostID) (map[domain.PostID]int, error)); ok {
		return returnFunc(ctx, postIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.PostID) map[domain.PostID]int); ok {
		r0 = returnFunc(ctx, postIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[domain.PostID]int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []domain.PostID) error); ok {
		r1 = returnFunc(ctx, postIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CommentRepository_BatchCountTopLevel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchCountTopLevel'
type CommentRepository_BatchCountTopLevel_Call struct {
	*mock.Call
}

// BatchCountTopLevel is a helper method to define mock.On call
//   - ctx context.Context
//   - postIDs []domain.PostID
func (_e *CommentRepository_Expecter) BatchCountTopLevel(ctx interface{}, postIDs interface{}) *CommentRepository_BatchCountTopLevel_Call {
	return &CommentRepository_BatchCountTopLevel_Call{Call: _e.mock.On("BatchCountTopLevel", ctx, postIDs)}
}

func (_c *CommentRepository_BatchCountTopLevel_Call) Run(run func(ctx context.Context, postIDs []domain.PostID)) *CommentRepository_BatchCountTopLevel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []domain.PostID
		if args[1] != nil {
			arg1 = args[1].([]domain.PostID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CommentRepository_BatchCountTopLevel_Call) Return(postIDToInt map[domain.PostID]int, err error) *CommentRepository_BatchCountTopLevel_Call {
	_c.Call.Return(postIDToInt, err)
	return _c
}

func (_c *CommentRepository_BatchCountTopLevel_Call) RunAndReturn(run func(ctx context.Context, postIDs []domain.PostID) (map[domain.PostID]int, error)) *CommentRepository_BatchCountTopLevel_Call {
	_c.Call.Return(run)
	return _c
}

// BatchListReplies provides a mock function for the type CommentRepository
func (_mock *CommentRepository) BatchListReplies(ctx context.Context, parentIDs []domain.CommentID, page domain.PageInput) (map[domain.CommentID]domain.Page[domain.Comment], error) {
	ret := _mock.Called(ctx, parentIDs, page)

	if len(ret) == 0 {
		panic("no return value specified for BatchListReplies")
	}

	var r0 map[domain.CommentID]domain.Page[domain.Comment]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.CommentID, domain.PageInput) (map[domain.CommentID]domain.Page[domain.Comment], error)); ok {
		return returnFunc(ctx, parentIDs, page)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.CommentID, domain.PageInput) map[domain.CommentID]domain.Page[domain.Comment]); ok {
		r0 = returnFunc(ctx, parentIDs, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[domain.CommentID]domain.Page[domain.Comment])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []domain.CommentID, domain.PageInput) error); ok {
		r1 = returnFunc(ctx, parentIDs, page)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CommentRepository_BatchListReplies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchListReplies'
type CommentRepository_BatchListReplies_Call struct {
	*mock.Call
}

// BatchListReplies is a helper method to define mock.On call
//   - ctx context.Context
//   - parentIDs []domain.CommentID
//   - page domain.PageInput
func (_e *CommentRepository_Expecter) BatchListReplies(ctx interface{}, parentIDs interface{}, page interface{}) *CommentRepository_BatchListReplies_Call {
	return &CommentRepository_BatchListReplies_Call{Call: _e.mock.On("BatchListReplies", ctx, parentIDs, page)}
}

func (_c *CommentRepository_BatchListReplies_Call) Run(run func(ctx context.Context, parentIDs []domain.CommentID, page domain.PageInput)) *CommentRepository_BatchListReplies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []domain.CommentID
		if args[1] != nil {
			arg1 = args[1].([]domain.CommentID)
		}
		var arg2 domain.PageInput
		if args[2] != nil {
			arg2 = args[2].(domain.PageInput)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CommentRepository_BatchListReplies_Call) Return(commentIDToPage map[domain.CommentID]domain.Page[domain.Comment], err error) *CommentRepository_BatchListReplies_Call {
	_c.Call.Return(commentIDToPage, err)
	return _c
}

func (_c *CommentRepository_BatchListReplies_Call) RunAndReturn(run func(ctx context.Context, parentIDs []domain.CommentID, page domain.PageInput) (map[domain.CommentID]domain.Page[domain.Comment], error)) *CommentRepository_BatchListReplies_Call {
	_c.Call.Return(run)
	return _c
}

// BatchListTopLevel provides a mock function for the type CommentRepository
func (_mock *CommentRepository) BatchListTopLevel(ctx context.Context, postIDs []domain.PostID, page domain.PageInput) (map[domain.PostID]domain.Page[domain.Comment], error) {
	ret := _mock.Called(ctx, postIDs, page)

	if len(ret) == 0 {
		panic("no return value specified for BatchListTopLevel")
	}

	var r0 map[domain.PostID]domain.Page[domain.Comment]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.PostID, domain.PageInput) (map[domain.PostID]domain.Page[domain.Comment], error)); ok {
		return returnFunc(ctx, postIDs, page)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.PostID, domain.PageInput) map[domain.PostID]domain.Page[domain.Comment]); ok {
		r0 = returnFunc(ctx, postIDs, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[domain.PostID]domain.Page[domain.Comment])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []domain.PostID, domain.PageInput) error); ok {
		r1 = returnFunc(ctx, postIDs, page)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CommentRepository_BatchListTopLevel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchListTopLevel'
type CommentRepository_BatchListTopLevel_Call struct {
	*mock.Call
}

// BatchListTopLevel is a helper method to define mock.On call
//   - ctx context.Context
//   - postIDs []domain.PostID
//   - page domain.PageInput
func (_e *CommentRepository_Expecter) BatchListTopLevel(ctx interface{}, postIDs interface{}, page interface{}) *CommentRepository_BatchListTopLevel_Call {
	return &CommentRepository_BatchListTopLevel_Call{Call: _e.mock.On("BatchListTopLevel", ctx, postIDs, page)}
}

func (_c *CommentRepository_BatchListTopLevel_Call) Run(run func(ctx context.Context, postIDs []domain.PostID, page domain.PageInput)) *CommentRepository_BatchListTopLevel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []domain.PostID
		if args[1] != nil {
			arg1 = args[1].([]domain.PostID)
		}
		var arg2 domain.PageInput
		if args[2] != nil {
			arg2 = args[2].(domain.PageInput)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CommentRepository_BatchListTopLevel_Call) Return(postIDToPage map[domain.PostID]domain.Page[domain.Comment], err error) *CommentRepository_BatchListTopLevel_Call {
	_c.Call.Return(postIDToPage, err)
	return _c
}

func (_c *CommentRepository_BatchListTopLevel_Call) RunAndReturn(run func(ctx context.Context, postIDs []domain.PostID, page domain.PageInput) (map[domain.PostID]domain.Page[domain.Comment], error)) *CommentRepository_BatchListTopLevel_Call {
	_c.Call.Return(run)
	return _c
}

// CountReplies provides a mock function for the type CommentRepository
func (_mock *CommentRepository) CountReplies(ctx context.Context, parentID domain.CommentID) (int, error) {
	ret := _mock.Called(ctx, parentID)

	if len(ret) == 0 {
		panic("no return value specified for CountReplies")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.CommentID) (int, error)); ok {
		return returnFunc(ctx, parentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.CommentID) int); ok {
		r0 = returnFunc(ctx, parentID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.CommentID) error); ok {
		r1 = returnFunc(ctx, parentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CommentRepository_CountReplies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountReplies'
type CommentRepository_CountReplies_Call struct {
	*mock.Call
}

// CountReplies is a helper method to define mock.On call
//   - ctx context.Context
//   - parentID domain.CommentID
func (_e *CommentRepository_Expecter) CountReplies(ctx interface{}, parentID interface{}) *CommentRepository_CountReplies_Call {
	return &CommentRepository_CountReplies_Call{Call: _e.mock.On("CountReplies", ctx, parentID)}
}

func (_c *CommentRepository_CountReplies_Call) Run(run func(ctx context.Context, parentID domain.CommentID)) *CommentRepository_CountReplies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.CommentID
		if args[1] != nil {
			arg1 = args[1].(domain.CommentID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CommentRepository_CountReplies_Call) Return(n int, err error) *CommentRepository_CountReplies_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *CommentRepository_CountReplies_Call) RunAndReturn(run func(ctx context.Context, parentID domain.CommentID) (int, error)) *CommentRepository_CountReplies_Call {
	_c.Call.Return(run)
	return _c
}

// CountTopLevel provides a mock function for the type CommentRepository
func (_mock *CommentRepository) CountTopLevel(ctx context.Context, postID domain.PostID) (int, error) {
	ret := _mock.Called(ctx, postID)

	if len(ret) == 0 {
		panic("no return value specified for CountTopLevel")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PostID) (int, error)); ok {
		return returnFunc(ctx, postID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PostID) int); ok {
		r0 = returnFunc(ctx, postID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.PostID) error); ok {
		r1 = returnFunc(ctx, postID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CommentRepository_CountTopLevel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountTopLevel'
type CommentRepository_CountTopLevel_Call struct {
	*mock.Call
}

// CountTopLevel is a helper method to define mock.On call
//   - ctx context.Context
//   - postID domain.PostID
func (_e *CommentRepository_Expecter) CountTopLevel(ctx interface{}, postID interface{}) *CommentRepository_CountTopLevel_Call {
	return &CommentRepository_CountTopLevel_Call{Call: _e.mock.On("CountTopLevel", ctx, postID)}
}

func (_c *CommentRepository_CountTopLevel_Call) Run(run func(ctx context.Context, postID domain.PostID)) *CommentRepository_CountTopLevel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PostID
		if args[1] != nil {
			arg1 = args[1].(domain.PostID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CommentRepository_CountTopLevel_Call) Return(n int, err error) *CommentRepository_CountTopLevel_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *CommentRepository_CountTopLevel_Call) RunAndReturn(run func(ctx context.Context, postID domain.PostID) (int, error)) *CommentRepository_CountTopLevel_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type CommentRepository
func (_mock *CommentRepository) Create(ctx context.Context, comment domain.Comment) error {
	ret := _mock.Called(ctx, comment)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Comment) error); ok {
		r0 = returnFunc(ctx, comment)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CommentRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type CommentRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - comment domain.Comment
func (_e *CommentRepository_Expecter) Create(ctx interface{}, comment interface{}) *CommentRepository_Create_Call {
	return &CommentRepository_Create_Call{Call: _e.mock.On("Create", ctx, comment)}
}

func (_c *CommentRepository_Create_Call) Run(run func(ctx context.Context, comment domain.Comment)) *CommentRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Comment
		if args[1] != nil {
			arg1 = args[1].(domain.Comment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CommentRepository_Create_Call) Return(err error) *CommentRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CommentRepository_Create_Call) RunAndReturn(run func(ctx context.Context, comment domain.Comment) error) *CommentRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type CommentRepository
func (_mock *CommentRepository) GetByID(ctx context.Context, id domain.CommentID) (domain.Comment, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.Comment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.CommentID) (domain.Comment, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.CommentID) domain.Comment); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Comment)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.CommentID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CommentRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type CommentRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.CommentID
func (_e *CommentRepository_Expecter) GetByID(ctx interface{}, id interface{}) *CommentRepository_GetByID_Call {
	return &CommentRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *CommentRepository_GetByID_Call) Run(run func(ctx context.Context, id domain.CommentID)) *CommentRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.CommentID
		if args[1] != nil {
			arg1 = args[1].(domain.CommentID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CommentRepository_GetByID_Call) Return(comment domain.Comment, err error) *CommentRepository_GetByID_Call {
	_c.Call.Return(comment, err)
	return _c
}

func (_c *CommentRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id domain.CommentID) (domain.Comment, error)) *CommentRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListReplies provides a mock function for the type CommentRepository
func (_mock *CommentRepository) ListReplies(ctx context.Context, parentID domain.CommentID, page domain.PageInput) (domain.Page[domain.Comment], error) {
	ret := _mock.Called(ctx, parentID, page)

	if len(ret) == 0 {
		panic("no return value specified for ListReplies")
	}

	var r0 domain.Page[domain.Comment]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.CommentID, domain.PageInput) (domain.Page[domain.Comment], error)); ok {
		return returnFunc(ctx, parentID, page)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.CommentID, domain.PageInput) domain.Page[domain.Comment]); ok {
		r0 = returnFunc(ctx, parentID, page)
	} else {
		r0 = ret.Get(0).(domain.Page[domain.Comment])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.CommentID, domain.PageInput) error); ok {
		r1 = returnFunc(ctx, parentID, page)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CommentRepository_ListReplies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListReplies'
type CommentRepository_ListReplies_Call struct {
	*mock.Call
}

// ListReplies is a helper method to define mock.On call
//   - ctx context.Context
//   - parentID domain.CommentID
//   - page domain.PageInput
func (_e *CommentRepository_Expecter) ListReplies(ctx interface{}, parentID interface{}, page interface{}) *CommentRepository_ListReplies_Call {
	return &CommentRepository_ListReplies_Call{Call: _e.mock.On("ListReplies", ctx, parentID, page)}
}

func (_c *CommentRepository_ListReplies_Call) Run(run func(ctx context.Context, parentID domain.CommentID, page domain.PageInput)) *CommentRepository_ListReplies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.CommentID
		if args[1] != nil {
			arg1 = args[1].(domain.CommentID)
		}
		var arg2 domain.PageInput
		if args[2] != nil {
			arg2 = args[2].(domain.PageInput)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CommentRepository_ListReplies_Call) Return(page1 domain.Page[domain.Comment], err error) *CommentRepository_ListReplies_Call {
	_c.Call.Return(page1, err)
	return _c
}

func (_c *CommentRepository_ListReplies_Call) RunAndReturn(run func(ctx context.Context, parentID domain.CommentID, page domain.PageInput) (domain.Page[domain.Comment], error)) *CommentRepository_ListReplies_Call {
	_c.Call.Return(run)
	return _c
}

// ListTopLevel provides a mock function for the type CommentRepository
func (_mock *CommentRepository) ListTopLevel(ctx context.Context, postID domain.PostID, page domain.PageInput) (domain.Page[domain.Comment], error) {
	ret := _mock.Called(ctx, postID, page)

	if len(ret) == 0 {
		panic("no return value specified for ListTopLevel")
	}

	var r0 domain.Page[domain.Comment]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PostID, domain.PageInput) (domain.Page[domain.Comment], error)); ok {
		return returnFunc(ctx, postID, page)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PostID, domain.PageInput) domain.Page[domain.Comment]); ok {
		r0 = returnFunc(ctx, postID, page)
	} else {
		r0 = ret.Get(0).(domain.Page[domain.Comment])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.PostID, domain.PageInput) error); ok {
		r1 = returnFunc(ctx, postID, page)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CommentRepository_ListTopLevel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTopLevel'
type CommentRepository_ListTopLevel_Call struct {
	*mock.Call
}

// ListTopLevel is a helper method to define mock.On call
//   - ctx context.Context
//   - postID domain.PostID
//   - page domain.PageInput
func (_e *CommentRepository_Expecter) ListTopLevel(ctx interface{}, postID interface{}, page interface{}) *CommentRepository_ListTopLevel_Call {
	return &CommentRepository_ListTopLevel_Call{Call: _e.mock.On("ListTopLevel", ctx, postID, page)}
}

func (_c *CommentRepository_ListTopLevel_Call) Run(run func(ctx context.Context, postID domain.PostID, page domain.PageInput)) *CommentRepository_ListTopLevel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PostID
		if args[1] != nil {
			arg1 = args[1].(domain.PostID)
		}
		var arg2 domain.PageInput
		if args[2] != nil {
			arg2 = args[2].(domain.PageInput)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CommentRepository_ListTopLevel_Call) Return(page1 domain.Page[domain.Comment], err error) *CommentRepository_ListTopLevel_Call {
	_c.Call.Return(page1, err)
	return _c
}

func (_c *CommentRepository_ListTopLevel_Call) RunAndReturn(run func(ctx context.Context, postID domain.PostID, page domain.PageInput) (domain.Page[domain.Comment], error)) *CommentRepository_ListTopLevel_Call {
	_c.Call.Return(run)
	return _c
}
