// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package applicationmocks

import (
	"context"

	"github.com/Matthew11K/Comments-Service/internal/application"
	mock "github.com/stretchr/testify/mock"
)

// NewCommentEventPublisher creates a new instance of CommentEventPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommentEventPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *CommentEventPublisher {
	mock := &CommentEventPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CommentEventPublisher is an autogenerated mock type for the CommentEventPublisher type
type CommentEventPublisher struct {
	mock.Mock
}

type CommentEventPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *CommentEventPublisher) EXPECT() *CommentEventPublisher_Expecter {
	return &CommentEventPublisher_Expecter{mock: &_m.Mock}
}

// PublishCommentAdded provides a mock function for the type CommentEventPublisher
func (_mock *CommentEventPublisher) PublishCommentAdded(ctx context.Context, event application.CommentAddedEvent) {
	_mock.Called(ctx, event)
	return
}

// CommentEventPublisher_PublishCommentAdded_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishCommentAdded'
type CommentEventPublisher_PublishCommentAdded_Call struct {
	*mock.Call
}

// PublishCommentAdded is a helper method to define mock.On call
//   - ctx context.Context
//   - event application.CommentAddedEvent
func (_e *CommentEventPublisher_Expecter) PublishCommentAdded(ctx interface{}, event interface{}) *CommentEventPublisher_PublishCommentAdded_Call {
	return &CommentEventPublisher_PublishCommentAdded_Call{Call: _e.mock.On("PublishCommentAdded", ctx, event)}
}

func (_c *CommentEventPublisher_PublishCommentAdded_Call) Run(run func(ctx context.Context, event application.CommentAddedEvent)) *CommentEventPublisher_PublishCommentAdded_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 application.CommentAddedEvent
		if args[1] != nil {
			arg1 = args[1].(application.CommentAddedEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CommentEventPublisher_PublishCommentAdded_Call) Return() *CommentEventPublisher_PublishCommentAdded_Call {
	_c.Call.Return()
	return _c
}

func (_c *CommentEventPublisher_PublishCommentAdded_Call) RunAndReturn(run func(ctx context.Context, event application.CommentAddedEvent)) *CommentEventPublisher_PublishCommentAdded_Call {
	_c.Run(run)
	return _c
}
