// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package applicationmocks

import (
	"context"

	"github.com/Matthew11K/Comments-Service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewPostRepository creates a new instance of PostRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPostRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PostRepository {
	mock := &PostRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PostRepository is an autogenerated mock type for the PostRepository type
type PostRepository struct {
	mock.Mock
}

type PostRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PostRepository) EXPECT() *PostRepository_Expecter {
	return &PostRepository_Expecter{mock: &_m.Mock}
}

// Count provides a mock function for the type PostRepository
func (_mock *PostRepository) Count(ctx context.Context) (int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PostRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type PostRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
func (_e *PostRepository_Expecter) Count(ctx interface{}) *PostRepository_Count_Call {
	return &PostRepository_Count_Call{Call: _e.mock.On("Count", ctx)}
}

func (_c *PostRepository_Count_Call) Run(run func(ctx context.Context)) *PostRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PostRepository_Count_Call) Return(n int, err error) *PostRepository_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *PostRepository_Count_Call) RunAndReturn(run func(ctx context.Context) (int, error)) *PostRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type PostRepository
func (_mock *PostRepository) Create(ctx context.Context, post domain.Post) error {
	ret := _mock.Called(ctx, post)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Post) error); ok {
		r0 = returnFunc(ctx, post)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PostRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type PostRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - post domain.Post
func (_e *PostRepository_Expecter) Create(ctx interface{}, post interface{}) *PostRepository_Create_Call {
	return &PostRepository_Create_Call{Call: _e.mock.On("Create", ctx, post)}
}

func (_c *PostRepository_Create_Call) Run(run func(ctx context.Context, post domain.Post)) *PostRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Post
		if args[1] != nil {
			arg1 = args[1].(domain.Post)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PostRepository_Create_Call) Return(err error) *PostRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PostRepository_Create_Call) RunAndReturn(run func(ctx context.Context, post domain.Post) error) *PostRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type PostRepository
func (_mock *PostRepository) GetByID(ctx context.Context, id domain.PostID) (domain.Post, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.Post
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PostID) (domain.Post, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PostID) domain.Post); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Post)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.PostID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PostRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type PostRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.PostID
func (_e *PostRepository_Expecter) GetByID(ctx interface{}, id interface{}) *PostRepository_GetByID_Call {
	return &PostRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *PostRepository_GetByID_Call) Run(run func(ctx context.Context, id domain.PostID)) *PostRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PostID
		if args[1] != nil {
			arg1 = args[1].(domain.PostID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PostRepository_GetByID_Call) Return(post domain.Post, err error) *PostRepository_GetByID_Call {
	_c.Call.Return(post, err)
	return _c
}

func (_c *PostRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id domain.PostID) (domain.Post, error)) *PostRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type PostRepository
func (_mock *PostRepository) List(ctx context.Context, page domain.PageInput) (domain.Page[domain.Post], error) {
	ret := _mock.Called(ctx, page)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 domain.Page[domain.Post]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PageInput) (domain.Page[domain.Post], error)); ok {
		return returnFunc(ctx, page)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PageInput) domain.Page[domain.Post]); ok {
		r0 = returnFunc(ctx, page)
	} else {
		r0 = ret.Get(0).(domain.Page[domain.Post])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.PageInput) error); ok {
		r1 = returnFunc(ctx, page)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PostRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type PostRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - page domain.PageInput
func (_e *PostRepository_Expecter) List(ctx interface{}, page interface{}) *PostRepository_List_Call {
	return &PostRepository_List_Call{Call: _e.mock.On("List", ctx, page)}
}

func (_c *PostRepository_List_Call) Run(run func(ctx context.Context, page domain.PageInput)) *PostRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PageInput
		if args[1] != nil {
			arg1 = args[1].(domain.PageInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PostRepository_List_Call) Return(page1 domain.Page[domain.Post], err error) *PostRepository_List_Call {
	_c.Call.Return(page1, err)
	return _c
}

func (_c *PostRepository_List_Call) RunAndReturn(run func(ctx context.Context, page domain.PageInput) (domain.Page[domain.Post], error)) *PostRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type PostRepository
func (_mock *PostRepository) Update(ctx context.Context, post domain.Post) error {
	ret := _mock.Called(ctx, post)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Post) error); ok {
		r0 = returnFunc(ctx, post)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PostRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type PostRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - post domain.Post
func (_e *PostRepository_Expecter) Update(ctx interface{}, post interface{}) *PostRepository_Update_Call {
	return &PostRepository_Update_Call{Call: _e.mock.On("Update", ctx, post)}
}

func (_c *PostRepository_Update_Call) Run(run func(ctx context.Context, post domain.Post)) *PostRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Post
		if args[1] != nil {
			arg1 = args[1].(domain.Post)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PostRepository_Update_Call) Return(err error) *PostRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PostRepository_Update_Call) RunAndReturn(run func(ctx context.Context, post domain.Post) error) *PostRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
